<template>
  <div>
      
  </div>
</template>

<script>

export default {
  data() {
    return {
      companySuggest: [
        //蘭嶼
        { value: '巴漾' },
        { value: '阿榮' },
        { value: '小豆丁' },
        { value: '嶼人' },
        { value: '阿樂本' },
        { value: '66' },
        { value: '五爪貝' },
        { value: '海王子' },
        { value: '日出東清' },
        { value: '石頭屋' },
        { value: '佳恩的家' },
        { value: '椰油灣' },
        { value: '漁人碼頭' },
        { value: '藍的魚' },
        { value: '藍翔' },
        { value: '鎮蘭居' },
        { value: '冠城' },
        { value: '八代灣' },
        { value: '海人魚' },
        { value: '海王子' },
        { value: 'TaTaLa的家' },
        { value: '悠遊蘭嶼' },
        { value: '避風港' },
        { value: '兩隻魚' },
        { value: '友達' },
        { value: '巴拉冠' },
        { value: '愛海' },
        { value: '我家的' },
        { value: '法艾' },
        { value: '紅不讓' },
        { value: '雨的家' },
        { value: '夜光貝' },
        { value: '海底城' },
        //綠島
        { value: '亞曼尼' },
        { value: '漁村' },
        { value: '馨滿園' },
        { value: '安德' },
        { value: '旅島' },
        { value: '海山' },
        { value: '小黑(趙國忠)' },
        { value: '海洋渡假村' },
        { value: '凱薪' },
        { value: '小美' },
        { value: '幸福月光' },
        { value: '悅軒' },         
        { value: '統祥' },
        { value: '船長之家' },
        { value: '晶華' },
        { value: '晶龍' },
        { value: '微風' },
        { value: '同心圓' },
        { value: '綠悠島' },
        { value: '南海民宿' },
        { value: '象緣' },
        { value: '海洋之家' },
        { value: '綠堤' },
        //馬祖
        { value: '依金那' },
        { value: '海浪花' },
        { value: '蓮園' },
        { value: '馬港' },
        { value: '船老大' },
        { value: '藍映' },
        { value: '芹壁25號' },
        { value: '天后會館' },
        { value: '白日夢' },
        { value: '五五據點' },
        { value: '香格里拉' },
        { value: '06據點' },
        { value: '大新' },         
        { value: '家適' },
        { value: '福華' },
        { value: '美芹居' },
        { value: '邊辰' },
        { value: '木喜' },
        { value: '北極星' },
        { value: '台江' },
        { value: '馬蓋先' },
        { value: '覓境' },
        { value: '凱翔' },
        { value: '卡蹓' },
        { value: '田園山莊' }, 
        { value: '東方明珠' },
        { value: '北海岸' },
        { value: '玖伍小築' },
        { value: '田園山莊' },
        { value: '宏瑞' },
        { value: '故鄉' },
        { value: '幸福居' },
        { value: '藍洋洋的家' },
        { value: '星馬' },
        { value: '幸福海岸' },
        { value: '發哥' },
        { value: '達露岸' },         
        { value: '富喜' },
        //金門
        { value: '叮叮車' },
        { value: '金翔' },
        { value: '瀚裕坊' },
        { value: '戴家' },
        { value: '海豚灣(鎮西)' },
        { value: '金豐' },
        { value: '吉品' },
        { value: '三德' },
        { value: '823行館' },
        { value: '小金門' },
        { value: '四海會館' }, 
        { value: '宏福' },
        { value: '金沙大地' },
        { value: '金沙假日' },
        { value: '金沙湖畔' },
        { value: '金金禮寓' },
        { value: '海福花園' },
        { value: '閩南' },
        { value: '海灣' },
        { value: 'IN99' },
        { value: '阿花的家' },
        { value: '上善若水' },
        { value: '海院子' },         
        { value: '大雁(福華)' },
        { value: '冠城' },
        { value: '時光旅舍' },
        { value: '金湖' },
        //澎湖
        { value: '宏瑞' },
        { value: '故鄉' },
        { value: '幸福居' },
        { value: '藍洋洋的家' },
        { value: '星馬' },
        { value: '幸福海岸' },
        { value: '發哥' },
        { value: '達露岸' }, 
        { value: '富喜' },
        { value: '金沙灘' },
        { value: '南海' },
        { value: '戀夏' },
        { value: '東安(夜釣)' },
        { value: '小丑魚 (海牧)' },
        { value: '行雲(海底漫步)' },
        { value: '東北' },
        { value: '旗豐' },
        { value: '銀海' },
        { value: '紫晶灣' },
        { value: '日辰' },         
        { value: '光志' },
        { value: '馬公四海' },
        { value: '菜園' },
        { value: '海天下' },
        { value: '百慶' },
        { value: '信誼' },
        { value: '豐谷' },
        { value: '溫馨' },
        { value: '喜來登' },
        { value: '澎澄' },
        { value: '馬公老街' },
        { value: '長春' }, 
        { value: '金八達' },
        { value: '安一' },
        { value: '君洋' },
        { value: '傻風' },
        { value: '豐國' },
        { value: '勝國' },
        { value: '慶霖' },
        { value: '愛丁堡' },
        { value: '佳美' },
        { value: '休閒工坊' },
        { value: '海安' },
        { value: '海上皇宮' },         
        { value: '海洋渡假村' },
        { value: '沐光之居' },
        { value: '幸福陽光' },
        { value: '星月小樓' },
        { value: '澎湖灣行旅' },
        { value: '臨海居' },
        { value: '海岸情' },
        { value: '海悅' },
        { value: '安泊' },
        //交通
        { value: '綠島之星' },
        { value: '滿天星' },
        { value: '海馬' }, 
        { value: '百麗' },
        { value: '立榮' },
        { value: '華信' },
        { value: '德安' },
        { value: '大發(金星)' },
        { value: '龍族' },         
        { value: '協信' },
        { value: '耐斯' },
        { value: '狄成' },
        { value: '運通' },
        { value: '瑋鑫' },
        { value: '樂遊台灣(500)' },
        { value: '萬德' },
        { value: '恆春' },
        { value: '洪嘉' },
        { value: '乘紘' },
        { value: '京典' },
        { value: '元美' }, 
        { value: '全球' },
        { value: '今冠' },
        { value: '永達' },
        { value: '向上' },
        { value: '宥瀧' },
        { value: '家佳' },         
        { value: '建民' },
        { value: '鎰成' },
        { value: '世界聯合' },
        { value: '利達' },
        { value: '金翔亮' },
        //TS
        { value: '佳期' },
        { value: '金明生' },
        { value: '星凱' },
        { value: '八八' },
        { value: '天海' },
        { value: '寶豐' },
        { value: '鼎運' }, 
        { value: '巨登' },
        { value: '捷利' },
        { value: '山富' },
        { value: '尊采' },
        { value: '安順' },
        { value: '西南' },         
        { value: '百利' },
        { value: '吉航' },
        { value: '大眾' },
        { value: '大都會' },
        { value: '永久' },
      ],
    }
  },
  created() {
    
  },
  methods: {

  },
  mounted(){
    
  }
}
</script>


