<template>
  <div>
      
  </div>
</template>

<script>

export default {
  data() {
    return {
      companySuggest: [
        //蘭嶼
        { value: '巴漾'       ,other:'月結'},
        { value: '阿榮'       ,other:'月結'},
        { value: '小豆丁'     ,other:'非月結'},
        { value: '嶼人'       ,other:'非月結'},
        { value: '阿樂本'     ,other:'非月結'},
        { value: '66'         ,other:'非月結'},
        { value: '五爪貝'     ,other:'非月結'},
        { value: '海王子'     ,other:'非月結'},
        { value: '日出東清'   ,other:'非月結'},
        { value: '石頭屋'     ,other:'非月結'},
        { value: '佳恩的家'   ,other:'非月結'},
        { value: '椰油灣'     ,other:'非月結'},
        { value: '漁人碼頭'   ,other:'非月結'},
        { value: '藍的魚'     ,other:'非月結'},
        { value: '藍翔'       ,other:'非月結'},
        { value: '鎮蘭居'     ,other:'非月結'},
        { value: '八代灣'     ,other:'非月結'},
        { value: '海人魚'     ,other:'非月結'},
        { value: 'TALALA的家' ,other:'非月結'},
        { value: '悠遊蘭嶼'   ,other:'非月結'},
        { value: '避風港'     ,other:'非月結'},
        { value: '兩隻魚'     ,other:'非月結'},
        { value: '友達'       ,other:'非月結'},
        { value: '巴拉冠'     ,other:'非月結'},
        { value: '愛海'       ,other:'非月結'},
        { value: '我家的'     ,other:'非月結'},
        { value: '法艾'       ,other:'非月結'},
        { value: '紅不讓'     ,other:'非月結'},
        { value: '雨的家'     ,other:'非月結'},
        { value: '夜光貝'     ,other:'非月結'},
        { value: '海底城'     ,other:'非月結'},
        //綠島
        { value: '亞曼尼'     ,other:'月結'},
        { value: '漁村'       ,other:'月結'},
        { value: '馨滿園'     ,other:'月結'},
        { value: '安德'       ,other:'月結'},
        { value: '旅島'        ,other:'非月結'},
        { value: '海山'        ,other:'非月結'},
        { value: '小黑(趙國忠)',other:'非月結'},
        { value: '海洋渡假村'  ,other:'非月結'},
        { value: '凱薪'        ,other:'非月結'},
        { value: '小美'        ,other:'非月結'},
        { value: '幸福月光'    ,other:'非月結'},
        { value: '悅軒'        ,other:'非月結'},         
        { value: '統祥'        ,other:'非月結'},
        { value: '船長之家'    ,other:'非月結'},
        { value: '晶華'        ,other:'非月結'},
        { value: '晶龍'        ,other:'非月結'},
        { value: '微風'        ,other:'非月結'},
        { value: '同心圓'      ,other:'非月結'},
        { value: '綠悠島'      ,other:'非月結'},
        { value: '南海民宿'    ,other:'非月結'},
        { value: '象緣'        ,other:'非月結'},
        { value: '海洋之家'    ,other:'非月結'},
        { value: '綠堤'        ,other:'非月結'},
        { value: '嚕嚕米的家'   ,other:'非月結'},
        //馬祖
        { value: '依金那'      ,other:'月結'},
        { value: '海浪花'      ,other:'月結'},
        { value: '蓮園'        ,other:'月結'},
        { value: '馬港'        ,other:'非月結'},
        { value: '船老大'      ,other:'非月結'},
        { value: '藍映'        ,other:'非月結'},
        { value: '芹壁25號'    ,other:'非月結'},
        { value: '天后會館'    ,other:'非月結'},
        { value: '白日夢'      ,other:'非月結'},
        { value: '五五據點'    ,other:'非月結'},
        { value: '香格里拉'    ,other:'非月結'},
        { value: '06據點'      ,other:'非月結'},
        { value: '大新'        ,other:'非月結'},         
        { value: '家適'        ,other:'非月結'},
        { value: '福華'        ,other:'非月結'},
        { value: '美芹居'      ,other:'非月結'},
        { value: '邊辰'        ,other:'非月結'},
        { value: '木喜'        ,other:'非月結'},
        { value: '北極星'      ,other:'非月結'},
        { value: '台江'        ,other:'非月結'},
        { value: '馬蓋先'      ,other:'非月結'},
        { value: '覓境'        ,other:'非月結'},
        { value: '凱翔'        ,other:'非月結'},
        { value: '卡蹓'        ,other:'非月結'},
        { value: '田園山莊'    ,other:'非月結'}, 
        { value: '東方明珠'    ,other:'非月結'},
        { value: '北海岸'      ,other:'非月結'},
        { value: '玖伍小築'    ,other:'非月結'},
        { value: '田園山莊'    ,other:'非月結'},
        { value: '故鄉'        ,other:'非月結'},
        { value: '幸福居'      ,other:'非月結'},
        { value: '藍洋洋的家'  ,other:'非月結' },
        { value: '星馬'        ,other:'非月結'},
        { value: '幸福海岸'    ,other:'非月結'},
        { value: '發哥'        ,other:'非月結'},
        { value: '達露岸'      ,other:'非月結'},         
        { value: '富喜'        ,other:'非月結'},
        { value: '卡布里城堡'   ,other:'非月結'},
        { value: '福正'        ,other:'非月結'},
        { value: '雲津客棧'    ,other:'非月結'},
        { value: '涼山頂'      ,other:'非月結'},
        { value: '小舅媽'      ,other:'非月結'},
        { value: '土哥機車'    ,other:'非月結'},
        { value: '山海一家'    ,other:'非月結'},
        { value: '宏瑞大飯店'  ,other:'非月結' },
        { value: '百合'        ,other:'非月結'},
        { value: '芹壁地中海'  ,other:'非月結'},
        { value: '清水灣'      ,other:'非月結'},
        { value: '家適'        ,other:'非月結'},         
        { value: '舒漫活'      ,other:'非月結'},
        { value: '馬悠驛館'    ,other:'非月結' },
        { value: '望海樓'      ,other:'非月結'},
        { value: '新華航業'    ,other:'非月結'},
        { value: '碧雲天'      ,other:'非月結'},         
        { value: '台馬之星'    ,other:'非月結'},
        //金門
        { value: '叮叮車'        ,other:'月結'},
        { value: '金翔'          ,other:'月結'},
        { value: '瀚裕坊'        ,other:'月結'},
        { value: '戴家'          ,other:'月結'},
        { value: '海豚灣(鎮西)'  ,other:'月結'},
        { value: '金豐'          ,other:'非月結'},
        { value: '吉品'          ,other:'非月結'},
        { value: '三德'          ,other:'非月結'},
        { value: '823行館'       ,other:'非月結'},
        { value: '小金門'        ,other:'非月結'},
        { value: '四海會館'      ,other:'非月結'}, 
        { value: '宏福'          ,other:'非月結'},   
        { value: '金沙大地'      ,other:'非月結'},
        { value: '金沙假日'      ,other:'非月結'},
        { value: '金沙湖畔'      ,other:'非月結'},
        { value: '金金禮寓'      ,other:'非月結'},
        { value: '海福花園'      ,other:'非月結'},
        { value: '閩南'          ,other:'非月結'},
        { value: '海灣'          ,other:'非月結'},
        { value: 'IN99'          ,other:'非月結'},
        { value: '阿花的家'      ,other:'非月結'},
        { value: '上善若水'      ,other:'非月結'},
        { value: '海院子'        ,other:'非月結'},         
        { value: '大雁(福華)'    ,other:'非月結'},
        { value: '冠城'          ,other:'月結'},
        { value: '時光旅舍'      ,other:'非月結'},
        { value: '金湖'          ,other:'非月結'},
        { value: '番茄紅了'      ,other:'非月結'},
        { value: '海灣VILLA會館' ,other:'非月結'},
        { value: '麟閣旅店'      ,other:'非月結'},
        //澎湖
        { value: '金沙灘'         ,other:'月結'},
        { value: '南海'           ,other:'月結'},
        { value: '戀夏'           ,other:'月結'},
        { value: '東安(夜釣)'     ,other:'月結'},
        { value: '小丑魚 (海牧)'  ,other:'月結'},
        { value: '行雲(海底漫步)' ,other:'月結'},
        { value: '東北'           ,other:'月結'},
        { value: '旗豐'           ,other:'月結'},
        { value: '銀海'           ,other:'月結'},
        { value: '紫晶灣'         ,other:'月結'},
        { value: '日辰'           ,other:'月結'},         
        { value: '光志'           ,other:'月結'},
        { value: '馬公四海'       ,other:'月結'},
        { value: '菜園'           ,other:'月結'},
        { value: '海天下'         ,other:'月結'},
        { value: '百慶'           ,other:'非月結'},
        { value: '信誼'           ,other:'非月結'},
        { value: '豐谷'           ,other:'非月結'},
        { value: '溫馨'           ,other:'非月結'},
        { value: '喜來登'         ,other:'非月結'},
        { value: '澎澄'           ,other:'非月結'},
        { value: '馬公老街'       ,other:'非月結'},
        { value: '長春'           ,other:'非月結'}, 
        { value: '金八達'         ,other:'非月結'},
        { value: '安一'           ,other:'非月結'},
        { value: '君洋'           ,other:'非月結'},
        { value: '傻風'           ,other:'非月結'},
        { value: '豐國'           ,other:'非月結'},
        { value: '勝國'           ,other:'非月結'},
        { value: '慶霖'           ,other:'非月結'},
        { value: '愛丁堡'         ,other:'非月結'},
        { value: '佳美'           ,other:'非月結'},
        { value: '休閒工坊'       ,other:'非月結'},
        { value: '海安'           ,other:'非月結'},
        { value: '海上皇宮'       ,other:'非月結'},         
        { value: '海洋渡假村'     ,other:'非月結'},
        { value: '沐光之居'       ,other:'非月結'},
        { value: '幸福陽光'       ,other:'非月結'},
        { value: '星月小樓'       ,other:'非月結'},
        { value: '澎湖灣行旅'     ,other:'非月結'},
        { value: '臨海居'         ,other:'非月結'},
        { value: '海岸情'         ,other:'非月結'},
        { value: '海悅'           ,other:'非月結'},
        { value: '安泊'           ,other:'非月結'},
        { value: '大姐'           ,other:'非月結'},
        { value: '陽光沙灘'       ,other:'非月結'},
        { value: '海安'           ,other:'非月結'},
        //交通
        { value: '綠島之星'       ,other:'非月結'},
        { value: '滿天星'         ,other:'非月結'},
        { value: '海馬'           ,other:'非月結'}, 
        { value: '百麗'           ,other:'非月結'},
        { value: '立榮'           ,other:'非月結'},
        { value: '華信'           ,other:'非月結'},
        { value: '德安'           ,other:'非月結'},
        { value: '大發(金星)'     ,other:'非月結'},
        { value: '龍族'           ,other:'月結'},         
        { value: '協信'           ,other:'月結'},
        { value: '耐斯'           ,other:'月結'},
        { value: '狄成'           ,other:'月結'},
        { value: '運通'           ,other:'月結'},
        { value: '瑋鑫'           ,other:'月結'},
        { value: '樂遊台灣(500)'  ,other:'月結'},
        { value: '萬德'           ,other:'月結'},
        { value: '恆春'           ,other:'非月結'},
        { value: '洪嘉'           ,other:'非月結'},
        { value: '乘紘'           ,other:'非月結'},
        { value: '京典'           ,other:'非月結'},
        { value: '元美'           ,other:'非月結'}, 
        { value: '全球'           ,other:'非月結'},
        { value: '今冠'           ,other:'非月結'},
        { value: '永達'           ,other:'月結'},
        { value: '向上'           ,other:'月結'},
        { value: '宥瀧'           ,other:'月結'},
        { value: '家佳'           ,other:'月結'},         
        { value: '建民'           ,other:'非月結'},
        { value: '鎰成'           ,other:'非月結'},
        { value: '世界聯合'       ,other:'月結'},
        { value: '利達'           ,other:'非月結'},
        { value: '金翔亮'         ,other:'月結'},
        { value: '雙吉福氣'       ,other:'非月結'},
        { value: '丁叮'           ,other:'非月結'},
        { value: '凱旋'           ,other:'非月結'},
        { value: '林明億'         ,other:'非月結'}, 
        { value: '翁明釗'         ,other:'非月結'},
        { value: '葉志成'         ,other:'非月結'},
        //TS
        { value: '佳期'           ,other:'月結'},
        { value: '金明生'         ,other:'月結'},
        { value: '星凱'           ,other:'月結'},
        { value: '八八'           ,other:'月結'},
        { value: '天海'           ,other:'非月結'},
        { value: '寶豐'           ,other:'非月結'},
        { value: '鼎運'           ,other:'非月結'}, 
        { value: '巨登'           ,other:'非月結'},
        { value: '捷利'           ,other:'非月結'},
        { value: '山富'           ,other:'非月結'},
        { value: '尊采'           ,other:'非月結'},
        { value: '安順'           ,other:'非月結'},
        { value: '西南'           ,other:'非月結'},         
        { value: '百利'           ,other:'非月結'},
        { value: '吉航'           ,other:'非月結'},
        { value: '大眾'           ,other:'非月結'},
        { value: '大都會'         ,other:'非月結'},
        { value: '永久'           ,other:'非月結'},
        { value: '易飛網'         ,other:'非月結'},
        { value: '長汎'           ,other:'月結'},
        //訂房
        { value: 'AGODA'          ,other:'非月結'},
        { value: 'EXPEDIA'        ,other:'非月結' },
        { value: 'TRIP'           ,other:'非月結' },
        { value: 'BOOKING'        ,other:'非月結' },
        //小琉球
        { value: '琉夏萊'          ,other:'非月結'},
        { value: '黑皮會館'        ,other:'非月結'},
        { value: '阿惠'            ,other:'非月結'},
      ],
    }
  },
  created() {
    
  },
  methods: {

  },
  mounted(){

  }
}
</script>


